// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainTicketing.Database;

#nullable disable

namespace TrainTicketing.Database.Migrations
{
    [DbContext(typeof(TrainTicketingDbContext))]
    [Migration("20250211130558_TariffRangesSeedings")]
    partial class TariffRangesSeedings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TrainTicketing.Entities.Announcement", b =>
                {
                    b.Property<Guid>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AnnouncementId");

                    b.HasIndex("CreatedById");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("TrainTicketing.Entities.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReservationId");

                    b.HasIndex("RouteId");

                    b.HasIndex("TrainId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("TrainTicketing.Entities.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MainTerminalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<int>("TariffSchemaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MainTerminalId");

                    b.HasIndex("TariffSchemaId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("TrainTicketing.Entities.RouteDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DistanceFromMain")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("StationId");

                    b.ToTable("RouteDetails");
                });

            modelBuilder.Entity("TrainTicketing.Entities.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatId"));

                    b.Property<int>("SeatClass")
                        .HasColumnType("int");

                    b.Property<string>("SeatCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<Guid>("TrainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrainId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SeatId");

                    b.HasIndex("TrainId");

                    b.HasIndex("TrainId1");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("TrainTicketing.Entities.SeatReservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("ReservationId", "SeatId");

                    b.HasIndex("SeatId");

                    b.ToTable("SeatReservationDetails");
                });

            modelBuilder.Entity("TrainTicketing.Entities.Station", b =>
                {
                    b.Property<Guid>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.HasKey("StationId");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            StationId = new Guid("8f1fd997-1261-450b-912f-8c90650e49d5"),
                            StationName = "Bucuresti"
                        },
                        new
                        {
                            StationId = new Guid("08b824ab-8ac6-4b24-9872-95ff63b492bf"),
                            StationName = "Peris"
                        },
                        new
                        {
                            StationId = new Guid("0ed5992e-6dda-407a-8481-5233d26c64e0"),
                            StationName = "Crivina"
                        },
                        new
                        {
                            StationId = new Guid("6ca13ae5-67f1-413b-b5c2-d89efc164c57"),
                            StationName = "Ploiesti Vest"
                        },
                        new
                        {
                            StationId = new Guid("41ff5b07-7ef4-4daf-b2e2-bb9d653d8245"),
                            StationName = "Campina"
                        },
                        new
                        {
                            StationId = new Guid("0bfcdb5d-163b-4576-b285-f360d6b5bcba"),
                            StationName = "Comarnic"
                        },
                        new
                        {
                            StationId = new Guid("62c14434-9039-412e-9e36-dcbd7cbbae4f"),
                            StationName = "Sinaia"
                        },
                        new
                        {
                            StationId = new Guid("33024dc9-bf84-4651-94bd-02a774f43c5b"),
                            StationName = "Busteni"
                        },
                        new
                        {
                            StationId = new Guid("8daeb4c3-de43-4e5a-8e7e-f4645bb03441"),
                            StationName = "Azuga"
                        },
                        new
                        {
                            StationId = new Guid("a831ce86-f068-4753-ba68-c3f9c9443605"),
                            StationName = "Predeal"
                        },
                        new
                        {
                            StationId = new Guid("66a74a29-282f-4ff9-b5d6-2f49d3d3536f"),
                            StationName = "Brasov"
                        },
                        new
                        {
                            StationId = new Guid("4d739b70-baaf-4367-9a1a-9d91481e2762"),
                            StationName = "Pasarea"
                        },
                        new
                        {
                            StationId = new Guid("4dd2478d-9065-495c-8696-bd96a842d4a2"),
                            StationName = "Fundulea"
                        },
                        new
                        {
                            StationId = new Guid("717df56e-fe44-4544-b22e-95398bfb653a"),
                            StationName = "Lehliu Gara"
                        },
                        new
                        {
                            StationId = new Guid("49270139-4185-42e0-9dd9-19e632a4105c"),
                            StationName = "Ciulnita"
                        },
                        new
                        {
                            StationId = new Guid("760cf2a1-f42b-4169-8022-497a9826eea4"),
                            StationName = "Fetesti"
                        },
                        new
                        {
                            StationId = new Guid("dbf75826-aa0d-4431-a0b4-ff1228a0a886"),
                            StationName = "Buzau"
                        },
                        new
                        {
                            StationId = new Guid("2086698a-e330-439b-ab3d-4dea78c7e688"),
                            StationName = "Faurei"
                        },
                        new
                        {
                            StationId = new Guid("89825248-a590-4dbb-913a-fc37567c2765"),
                            StationName = "Tandarei"
                        },
                        new
                        {
                            StationId = new Guid("bd245552-935b-40a6-bf09-bdba25d09443"),
                            StationName = "Fetesti"
                        },
                        new
                        {
                            StationId = new Guid("4806be82-6db7-421c-89b5-d92861bb3fbc"),
                            StationName = "Medgidia"
                        },
                        new
                        {
                            StationId = new Guid("2d1f9718-ce63-4fc9-be0f-fa1d236d5b19"),
                            StationName = "Constanta"
                        },
                        new
                        {
                            StationId = new Guid("03905450-41ef-4639-9713-ba663c3773da"),
                            StationName = "Eforie Nord"
                        },
                        new
                        {
                            StationId = new Guid("45ac2f22-2dae-4d32-ad38-34be33fe6a83"),
                            StationName = "Eforie Sud"
                        },
                        new
                        {
                            StationId = new Guid("644540c4-421a-4c79-b1e8-a4c7c8767ac3"),
                            StationName = "Costinesti Tabara"
                        },
                        new
                        {
                            StationId = new Guid("24bb1e5a-4c25-442d-82d3-8ea74348da0f"),
                            StationName = "Neptun"
                        },
                        new
                        {
                            StationId = new Guid("18d9c104-e905-4de8-a4d7-eead496ac5a2"),
                            StationName = "Mangalia"
                        },
                        new
                        {
                            StationId = new Guid("d5d4784b-d3db-474f-aa8a-0508a27753b5"),
                            StationName = "Parc Mogosoaia"
                        },
                        new
                        {
                            StationId = new Guid("a419a47a-335d-4166-a744-3396142333ce"),
                            StationName = "Patinoar"
                        },
                        new
                        {
                            StationId = new Guid("542784d4-2297-4a15-b198-81d5f918c12e"),
                            StationName = "Otopeni"
                        },
                        new
                        {
                            StationId = new Guid("c93ed874-9c18-4869-8958-dce572502796"),
                            StationName = "Gradinari"
                        },
                        new
                        {
                            StationId = new Guid("55296397-fc75-4d01-ba49-d3c497596d37"),
                            StationName = "Vadu Lat"
                        },
                        new
                        {
                            StationId = new Guid("12279946-5418-4d15-baf9-4daee8566525"),
                            StationName = "Videle"
                        },
                        new
                        {
                            StationId = new Guid("ac266cf0-3f2c-4aef-baab-2de4d17b2a19"),
                            StationName = "Galateni"
                        },
                        new
                        {
                            StationId = new Guid("f2a36100-4f48-467d-a72b-36f47e0b90de"),
                            StationName = "Radoiesti"
                        },
                        new
                        {
                            StationId = new Guid("3ef9ccc2-4501-4d00-a5cd-b4f9b94b645d"),
                            StationName = "Rosiorii de Vede"
                        });
                });

            modelBuilder.Entity("TrainTicketing.Entities.TariffRanges", b =>
                {
                    b.Property<int>("TariffRangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TariffRangeId"));

                    b.Property<decimal?>("EndKm")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("PricePerKm")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<int>("SeatClass")
                        .HasColumnType("int");

                    b.Property<decimal>("StartKm")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<int>("TariffSchemaId")
                        .HasColumnType("int");

                    b.HasKey("TariffRangeId");

                    b.HasIndex("TariffSchemaId");

                    b.ToTable("TariffRangess");

                    b.HasData(
                        new
                        {
                            TariffRangeId = 1,
                            EndKm = 10m,
                            PricePerKm = 6.0m,
                            SeatClass = 1,
                            StartKm = 1m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 2,
                            EndKm = 20m,
                            PricePerKm = 7.5m,
                            SeatClass = 1,
                            StartKm = 11m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 3,
                            EndKm = 30m,
                            PricePerKm = 10.5m,
                            SeatClass = 1,
                            StartKm = 21m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 4,
                            EndKm = 40m,
                            PricePerKm = 12.5m,
                            SeatClass = 1,
                            StartKm = 31m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 5,
                            EndKm = 50m,
                            PricePerKm = 16.5m,
                            SeatClass = 1,
                            StartKm = 41m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 6,
                            EndKm = 60m,
                            PricePerKm = 17.5m,
                            SeatClass = 1,
                            StartKm = 51m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 7,
                            EndKm = 70m,
                            PricePerKm = 20.5m,
                            SeatClass = 1,
                            StartKm = 61m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 8,
                            EndKm = 80m,
                            PricePerKm = 23.0m,
                            SeatClass = 1,
                            StartKm = 71m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 9,
                            EndKm = 90m,
                            PricePerKm = 26.0m,
                            SeatClass = 1,
                            StartKm = 81m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 10,
                            EndKm = 100m,
                            PricePerKm = 28.0m,
                            SeatClass = 1,
                            StartKm = 91m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 11,
                            EndKm = 120m,
                            PricePerKm = 34.0m,
                            SeatClass = 1,
                            StartKm = 101m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 12,
                            EndKm = 140m,
                            PricePerKm = 39.5m,
                            SeatClass = 1,
                            StartKm = 121m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 13,
                            EndKm = 160m,
                            PricePerKm = 44.5m,
                            SeatClass = 1,
                            StartKm = 141m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 14,
                            EndKm = 180m,
                            PricePerKm = 51.5m,
                            SeatClass = 1,
                            StartKm = 161m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 15,
                            EndKm = 200m,
                            PricePerKm = 57.0m,
                            SeatClass = 1,
                            StartKm = 181m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 16,
                            EndKm = 250m,
                            PricePerKm = 65.0m,
                            SeatClass = 1,
                            StartKm = 201m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 17,
                            EndKm = 300m,
                            PricePerKm = 75.5m,
                            SeatClass = 1,
                            StartKm = 251m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 18,
                            EndKm = 350m,
                            PricePerKm = 86.5m,
                            SeatClass = 1,
                            StartKm = 301m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 19,
                            EndKm = 400m,
                            PricePerKm = 100.0m,
                            SeatClass = 1,
                            StartKm = 351m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 20,
                            EndKm = 500m,
                            PricePerKm = 121.0m,
                            SeatClass = 1,
                            StartKm = 401m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 21,
                            PricePerKm = 26.0m,
                            SeatClass = 1,
                            StartKm = 501m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 22,
                            EndKm = 10m,
                            PricePerKm = 4.0m,
                            SeatClass = 2,
                            StartKm = 1m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 23,
                            EndKm = 20m,
                            PricePerKm = 5.0m,
                            SeatClass = 2,
                            StartKm = 11m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 24,
                            EndKm = 30m,
                            PricePerKm = 7.0m,
                            SeatClass = 2,
                            StartKm = 21m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 25,
                            EndKm = 40m,
                            PricePerKm = 8.5m,
                            SeatClass = 2,
                            StartKm = 31m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 26,
                            EndKm = 50m,
                            PricePerKm = 11.0m,
                            SeatClass = 2,
                            StartKm = 41m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 27,
                            EndKm = 60m,
                            PricePerKm = 12.0m,
                            SeatClass = 2,
                            StartKm = 51m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 28,
                            EndKm = 70m,
                            PricePerKm = 14.0m,
                            SeatClass = 2,
                            StartKm = 61m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 29,
                            EndKm = 80m,
                            PricePerKm = 15.5m,
                            SeatClass = 2,
                            StartKm = 71m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 30,
                            EndKm = 90m,
                            PricePerKm = 17.5m,
                            SeatClass = 2,
                            StartKm = 81m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 31,
                            EndKm = 100m,
                            PricePerKm = 19.0m,
                            SeatClass = 2,
                            StartKm = 91m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 32,
                            EndKm = 120m,
                            PricePerKm = 23.0m,
                            SeatClass = 2,
                            StartKm = 101m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 33,
                            EndKm = 140m,
                            PricePerKm = 26.5m,
                            SeatClass = 2,
                            StartKm = 121m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 34,
                            EndKm = 160m,
                            PricePerKm = 30.0m,
                            SeatClass = 2,
                            StartKm = 141m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 35,
                            EndKm = 180m,
                            PricePerKm = 34.5m,
                            SeatClass = 2,
                            StartKm = 161m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 36,
                            EndKm = 200m,
                            PricePerKm = 38.0m,
                            SeatClass = 2,
                            StartKm = 181m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 37,
                            EndKm = 250m,
                            PricePerKm = 43.5m,
                            SeatClass = 2,
                            StartKm = 201m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 38,
                            EndKm = 300m,
                            PricePerKm = 50.5m,
                            SeatClass = 2,
                            StartKm = 251m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 39,
                            EndKm = 350m,
                            PricePerKm = 58.0m,
                            SeatClass = 2,
                            StartKm = 301m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 40,
                            EndKm = 400m,
                            PricePerKm = 67.0m,
                            SeatClass = 2,
                            StartKm = 351m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 41,
                            EndKm = 500m,
                            PricePerKm = 81.0m,
                            SeatClass = 2,
                            StartKm = 401m,
                            TariffSchemaId = 1
                        },
                        new
                        {
                            TariffRangeId = 42,
                            PricePerKm = 17.5m,
                            SeatClass = 2,
                            StartKm = 501m,
                            TariffSchemaId = 1
                        });
                });

            modelBuilder.Entity("TrainTicketing.Entities.TariffSchema", b =>
                {
                    b.Property<int>("TariffSchemaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TariffSchemaId"));

                    b.Property<string>("TariffSchemaName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TariffSchemaId");

                    b.ToTable("TariffSchemas");

                    b.HasData(
                        new
                        {
                            TariffSchemaId = 1,
                            TariffSchemaName = "Standard"
                        });
                });

            modelBuilder.Entity("TrainTicketing.Entities.Train", b =>
                {
                    b.Property<Guid>("TrainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TrainName")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<int>("TrainType")
                        .HasColumnType("int");

                    b.HasKey("TrainId");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrainTicketing.Entities.Announcement", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("TrainTicketing.Entities.Reservation", b =>
                {
                    b.HasOne("TrainTicketing.Entities.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainTicketing.Entities.Train", "Train")
                        .WithMany()
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("Train");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrainTicketing.Entities.Route", b =>
                {
                    b.HasOne("TrainTicketing.Entities.Station", "MainTerminal")
                        .WithMany()
                        .HasForeignKey("MainTerminalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainTicketing.Entities.TariffSchema", "TariffSchema")
                        .WithMany()
                        .HasForeignKey("TariffSchemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MainTerminal");

                    b.Navigation("TariffSchema");
                });

            modelBuilder.Entity("TrainTicketing.Entities.RouteDetail", b =>
                {
                    b.HasOne("TrainTicketing.Entities.Route", "Route")
                        .WithMany("RouteDetails")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainTicketing.Entities.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("TrainTicketing.Entities.Seat", b =>
                {
                    b.HasOne("TrainTicketing.Entities.Train", null)
                        .WithMany("Seats")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainTicketing.Entities.Train", "Train")
                        .WithMany()
                        .HasForeignKey("TrainId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Train");
                });

            modelBuilder.Entity("TrainTicketing.Entities.SeatReservation", b =>
                {
                    b.HasOne("TrainTicketing.Entities.Reservation", "Reservation")
                        .WithMany("SeatReservations")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainTicketing.Entities.Seat", "Seat")
                        .WithMany("SeatReservations")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("TrainTicketing.Entities.TariffRanges", b =>
                {
                    b.HasOne("TrainTicketing.Entities.TariffSchema", "TariffSchema")
                        .WithMany("TariffRanges")
                        .HasForeignKey("TariffSchemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TariffSchema");
                });

            modelBuilder.Entity("TrainTicketing.Entities.Reservation", b =>
                {
                    b.Navigation("SeatReservations");
                });

            modelBuilder.Entity("TrainTicketing.Entities.Route", b =>
                {
                    b.Navigation("RouteDetails");
                });

            modelBuilder.Entity("TrainTicketing.Entities.Seat", b =>
                {
                    b.Navigation("SeatReservations");
                });

            modelBuilder.Entity("TrainTicketing.Entities.TariffSchema", b =>
                {
                    b.Navigation("TariffRanges");
                });

            modelBuilder.Entity("TrainTicketing.Entities.Train", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
